import { createAsyncThunk } from "@reduxjs/toolkit";

export const getInquiryListThunk = createAsyncThunk(
  "getInquiryListThunk",
  async (params: "list" | "user", { rejectWithValue }) => {
    try {
      const listData = [
        {
          seq: 0,
          title: "hello I'm Korean",
          writer: "bob@aixinc.io",
          memberId: "123",
          contents: "<b>test1</b>",
          isAnswerd: true,
          registerDatetime: "2023-08-24T07:58:37.631Z",
          categoryName: "가이드",
          categoryCode: 0,
          answerContents: "<p>test answer1<p>",
          answerWriter: "bob@aixinc.io",
          adminId: "admin@aixinc.io",
          answerRegisterDatetime: "2023-08-24T07:58:37.631Z",
        },
        {
          seq: 1,
          title: "hello I'm Korean",
          writer: "bob@aixinc.io",
          memberId: "123",
          contents: "<b>test1</b>",
          isAnswerd: true,
          registerDatetime: "2023-08-24T07:58:37.631Z",
          categoryName: "가이드",
          categoryCode: 0,
          answerContents: "<p>test answer1<p>",
          answerWriter: "bob@aixinc.io",
          adminId: "admin@aixinc.io",
          answerRegisterDatetime: "2023-08-24T07:58:37.631Z",
        },
        {
          seq: 2,
          title: "hello I'm Korean",
          writer: "bob@aixinc.io",
          memberId: "123",
          contents: "<b>test1</b>",
          isAnswerd: true,
          registerDatetime: "2023-08-24T07:58:37.631Z",
          categoryName: "가이드",
          categoryCode: 0,
          answerContents: "<p>test answer1<p>",
          answerWriter: "bob@aixinc.io",
          adminId: "admin@aixinc.io",
          answerRegisterDatetime: "2023-08-24T07:58:37.631Z",
        },
        {
          seq: 3,
          title: "hello I'm Korean",
          writer: "bob@aixinc.io",
          memberId: "123",
          contents: "<b>test1</b>",
          isAnswerd: true,
          registerDatetime: "2023-08-24T07:58:37.631Z",
          categoryName: "가이드",
          categoryCode: 0,
          answerContents: "<p>test answer1<p>",
          answerWriter: "bob@aixinc.io",
          adminId: "admin@aixinc.io",
          answerRegisterDatetime: "2023-08-24T07:58:37.631Z",
        },
        {
          seq: 4,
          title: "hello I'm Korean",
          writer: "bob@aixinc.io",
          memberId: "123",
          contents: "<b>test1</b>",
          isAnswerd: true,
          registerDatetime: "2023-08-24T07:58:37.631Z",
          categoryName: "가이드",
          categoryCode: 0,
          answerContents: "<p>test answer1<p>",
          answerWriter: "bob@aixinc.io",
          adminId: "admin@aixinc.io",
          answerRegisterDatetime: "2023-08-24T07:58:37.631Z",
        },
        {
          seq: 5,
          title: "hello I'm Korean",
          writer: "bob@aixinc.io",
          memberId: "123",
          contents: "<b>test1</b>",
          isAnswerd: true,
          registerDatetime: "2023-08-24T07:58:37.631Z",
          categoryName: "가이드",
          categoryCode: 0,
          answerContents: "<p>test answer1<p>",
          answerWriter: "bob@aixinc.io",
          adminId: "admin@aixinc.io",
          answerRegisterDatetime: "2023-08-24T07:58:37.631Z",
        },
      ];
      const userListData = [
        {
          seq: 0,
          title: "hello I'm Korean",
          writer: "bob@aixinc.io",
          memberId: "123",
          contents: "<b>test1</b>",
          isAnswerd: true,
          registerDatetime: "2023-08-24T07:58:37.631Z",
          categoryName: "가이드",
          categoryCode: 0,
          answerContents: "<p>test answer1<p>",
          answerWriter: "bob@aixinc.io",
          adminId: "admin@aixinc.io",
          answerRegisterDatetime: "2023-08-24T07:58:37.631Z",
        },
        {
          seq: 1,
          title: "hello I'm Korean",
          writer: "bob@aixinc.io",
          memberId: "123",
          contents: "<b>test1</b>",
          isAnswerd: true,
          registerDatetime: "2023-08-24T07:58:37.631Z",
          categoryName: "가이드",
          categoryCode: 0,
          answerContents: "<p>test answer1<p>",
          answerWriter: "bob@aixinc.io",
          adminId: "admin@aixinc.io",
          answerRegisterDatetime: "2023-08-24T07:58:37.631Z",
        },
        {
          seq: 2,
          title: "hello I'm Korean",
          writer: "bob@aixinc.io",
          memberId: "123",
          contents: "<b>test1</b>",
          isAnswerd: true,
          registerDatetime: "2023-08-24T07:58:37.631Z",
          categoryName: "가이드",
          categoryCode: 0,
          answerContents: "<p>test answer1<p>",
          answerWriter: "bob@aixinc.io",
          adminId: "admin@aixinc.io",
          answerRegisterDatetime: "2023-08-24T07:58:37.631Z",
        },
      ];
      const response = await Promise.resolve(
        params === "list" ? listData : userListData
      );
      return response;
    } catch (error) {
      return rejectWithValue(error);
    }
  }
);
